name: 'Action_Initialization'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'EA8500'
  COMPILE_CONFIG: 
    description: 'CONFIG'
    required: true
    default: 'EA8500-20240424-remove-igmpproxy'
  FILES_CONFIG: 
    description: 
    required: false
    default: 'public'
runs:
  using: "composite"
  steps:
    - name: Show system
      shell: bash
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        ulimit -a
        
    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      shell: bash
      run: |
        sudo swapoff -a
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install rename
        sudo -E git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        sudo -E git config --global core.abbrev auto
        sudo timedatectl set-timezone "Asia/Shanghai"
        df -h
        
